### ISSUE TITLE
IsAny improvement

### ISSUE THREAD

**Issue by smmoosavi** [dsherret/conditional-type-checks#10]
```ts
export type IsAny<T> = 0 extends (1 & T) ? true : false;
```
source: [@material-ui/types](https://github.com/mui-org/material-ui/blob/dfe2779b8b6499ccd1922990ac9178d84e02f8b6/packages/material-ui-types/index.d.ts#L52)

**Comment by dsherret** [comment]
Nice! Do you want to submit a PR and add a comment to https://stackoverflow.com/a/49928360/3406963 in the code? If not I can do it soon.

Also, `IsUnknown` could be updated to use `IsAny` now.

**Comment by smmoosavi** [comment]
I will send PR
