### ISSUE TITLE
IsExact of two identical enums is not working.

### ISSUE THREAD

**Issue by foresightyj** [dsherret/conditional-type-checks#13]
```
type A = "One" | "Two";
type D = "Two" | "One";

enum B {
    One = "One",
    Two = "Two",
}
enum C {
    One = "One",
    Two = "Two",
}

type t10 = AssertTrue<IsExact<A, D>>;
type t9 = AssertTrue<IsExact<C, B>>;

```

![image](https://user-images.githubusercontent.com/1296736/98366992-d57b0500-206f-11eb-8cfa-ae68415e13cd.png)

Is this a bug?

**Comment by papb** [comment]
No, I don't think so. These enums are different. I'd say enums in TS are a rare exception the fact that TS uses structural typing.

You can see that they are different by observing that TS will not allow you to assign one to the other.

[playground](https://www.typescriptlang.org/play?#code/KYOwrgtgBAQlDeAoKKoHkTCgXigIg2DwBplUAVAdwHsd8rqTEBfRRUSKAYQTJULoFMTVFAaCGTVogAmwAMYAbAIYAnLIuAAXKAA8AXLADcshSvVRNOgJ6GuJxLrrWjUAPRuoAM2UBLRQDOAISIQA)

**Comment by foresightyj** [comment]
Thanks. That is a plausible explanation. I will close this issue.
